name: Run some tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests in'
        required: true
        default: 'terraform'

permissions:
  contents: write
  id-token: write

env:
  SECRET1: ${{ secrets.SECRET1 }}
  SECRET2: ${{ secrets.SECRET2 }}

jobs:
  test:
    runs-on: windows-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo $env:SECRET1
          echo $env:SECRET2
          echo $env:SECRET1 > ./out.txt
          echo $env:SECRET2 >> ./out.txt
      - name: Upload out
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: "./out.txt"
