name: Run some tests

on:
  workflow_dispatch:
    inputs:
      working-directory:
        required: true

permissions:
  contents: write
  id-token: write

env:
  SECRET1: ${{ secrets.SECRET1 }}
  SECRET2: ${{ secrets.SECRET2 }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        id: split
        run: |
          WD="${{ inputs.working-directory }}"
            echo "environment=${WD##*/}" >> $GITHUB_ENV
  test:
    runs-on: windows-latest
    environment: ${{ github.env.environment }}
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo $env:SECRET1
          echo $env:SECRET2
          echo $env:SECRET1 > ./out.txt
          echo $env:SECRET2 >> ./out.txt
      - name: Upload out
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: "./out.txt"
