name: Run some tests

on:
  workflow_dispatch:
    inputs:
      working-directory:
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        id: split
        run: |
          WD="${{ inputs.working-directory }}"
          echo "environment=${WD##*/}" >> "$GITHUB_OUTPUT"
          echo "${WD##*/}^"
    outputs:
      environment: ${{ steps.split.outputs.environment }}
  test:
    runs-on: windows-latest
    needs: setup
    environment: ${{ needs.setup.outputs.environment }}
    env:
      SECRET1: ${{ secrets.SECRET1 }}
      SECRET2: ${{ secrets.SECRET2 }}
    steps:
      - name: echo environment
        run: |
          echo ${{ needs.setup.outputs.environment }}
      - name: get secrets
        id: secrets
        run: |
          $value="jobsecret2"
          echo "::add-mask::$value"
          echo "SECRET2=$value" >> "$GITHUB_ENV"
          echo "SECRET3=$value" >> "$GITHUB_ENV"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo $env:SECRET1
          echo $env:SECRET2
          echo $env:SECRET3
          echo $env:SECRET1 > ./out.txt
          echo $env:SECRET2 >> ./out.txt
          echo $env:SECRET3 >> ./out.txt
      - name: Upload out
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: "./out.txt"
