name: Run some tests

on:
  workflow_dispatch:
    inputs:
      working-directory:
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        id: split
        run: |
          WD="${{ inputs.working-directory }}"
          echo "environment=${WD##*/}" >> "$GITHUB_OUTPUT"
          echo "${WD##*/}^"
      - name: Set secrets
        id: secret
        run: |
          echo "::add-mask::jobsecret2"
          echo "SECRET2=jobsecret2" >> "$GITHUB_OUTPUT"
    outputs:
      environment: ${{ steps.split.outputs.environment }}
      secret2: ${{ steps.secret.outputs.SECRET2 }}
  test:
    runs-on: windows-latest
    needs: setup
    environment: ${{ needs.setup.outputs.environment }}
    env:
      SECRET1: ${{ secrets.SECRET1 }}
      SECRET2: ${{ needs.setup.outputs.secret2 }}
    steps:
      - name: echo environment
        run: |
          echo ${{ needs.setup.outputs.environment }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo $env:SECRET1
          echo $env:SECRET2
          echo $env:SECRET1 > ./out.txt
          echo $env:SECRET2 >> ./out.txt
      - name: Upload out
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: "./out.txt"
